### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by cameroncooke** [Ometria/ometria.ios_sdk#1]
We're moving away from using Cocoapods for dependency management would it be possible to get SPM support?

**Comment by CataD256** [comment]
@cameroncooke Yes, we're working on it. Stay tuned :)

**Comment by CataD256** [comment]
@cameroncooke Unfortunately we are unable to finalize adding support for SPM. Ometria has FirebaseMessaging as a mandatory dependency, and currently Firebase does not support integrating Messaging using SPM. I will currently leave the issue opened, and address it as soon as FirebaseMessaging is compatible with Swift Package Manager. 
Sorry for the inconvenience!

**Comment by cameroncooke** [comment]
@CataD256 Hello, Firebase now supports `FirebaseMessaging` could you add SPM support as we need to migrate our Firebase dependencies to SPM but we can't as Ometria has an implicit dependency on the `FirebaseMessaging` cocoapod.

**Comment by cameroncooke** [comment]
@CataD256 I've opened a PR which adds support for SPM https://github.com/Ometria/ometria.ios_sdk/pull/7/files 😃

**Comment by CataD256** [comment]
hi @cameroncooke SPM is now supported on the master branch :) Check it out

**Comment by cameroncooke** [comment]
@CataD256 Thank you!
