### ISSUE TITLE
`trackProductCategoryViewedEvent(category:)` in docs doesn't exist in SDK

### ISSUE THREAD

**Issue by cameroncooke** [Ometria/ometria.ios_sdk#4]
The README.md refers to the event:

> Product Category Viewed
> A visitor clicks / taps / views / highlights or otherwise shows interest in a product category.
> 
> For example, a store sells clothing, and they tap on "Women's Footwear".
> 
> ```swift
> trackProductCategoryViewedEvent(category: String)
> ```

But this event doesn't appear in the public API of the SDK.

**Comment by CataD256** [comment]
Hi @cameroncooke!
We settled on using Firebase version >7.0.0 for now. We will soon move to version 8.0.0, but only after we manage to do some testing on our side. 
Please let us know if SPM works properly for you with Ometria SDK v1.1.2.
