### ISSUE TITLE
Can't use Ometria SDK as Firebase dependency doesn't match versioning requirements of main app target

### ISSUE THREAD

**Issue by cameroncooke** [Ometria/ometria.ios_sdk#9]
https://github.com/Ometria/ometria.ios_sdk/blob/5fc5f1cd8d9479ee86a9d1bfb56b577fde217469/Package.swift#L18

We're seeing:

```
Dependencies could not be resolved because root depends on 'ometria.ios_sdk' 1.1.0..<2.0.0.
'ometria.ios_sdk' >= 1.1.0 cannot be used because package 'ometria.ios_sdk' is required using a stable-version but 'ometria.ios_sdk' depends on an unstable-version package 'firebase-ios-sdk' and no versions of 'ometria.ios_sdk' match the requirement 1.1.1..<2.0.0.
```

We're using `Firebase@7.0.0` in our main app, whereas this Package uses an unstable version by specifying the branch name. The `firebase-spm` branch I don't believe is needed.

**Comment by cameroncooke** [comment]
The latest changes to the `Package.swift` still don't resolve this issue as the `Package.swift` file now requires unstable versions of Firebase from the `master` branch. I would argue that Ometria SDK needs to settle on a version of Firebase that is current or break the dependency on Firebase and add APIs to allow the SDK consumers to hook up Ometria and Firebase instead.

**Comment by CataD256** [comment]
Hi @cameroncooke!
We settled on using Firebase version >7.0.0 for now. We will soon move to version 8.0.0, but only after we manage to do some testing on our side.
Please let us know if SPM works properly for you with Ometria SDK v1.1.2.

**Comment by cameroncooke** [comment]
Thank you. We would consider a move to Firebase 8 as a breaking change. If you proceed could you bump Ometria to version 2.x to allow us time to migrate?
